[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://api.replicate.com/v1/:splat"
  status = 200
  force = true
  headers = {Authorization = "Bearer ${REPLICATE_API_TOKEN}"}
